# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    indices:
        - name: articles
          class: App\Entity\Articles

#        - name:
#          class: App\Entity\Comment
